export const COMPLETION_SHELLS = ['bash', 'zsh'] as const;
const MAINTENANCE_PRUNE_FLAGS = ['--dry-run', '--max-age-days', '--dir', '--json'] as const;
const MAINTENANCE_BACKUP_FLAGS = ['--dir', '--out', '--json'] as const;

export type CompletionShell = (typeof COMPLETION_SHELLS)[number];

interface CommandCompletion {
  name: string;
  subcommands?: readonly string[];
  flags?: readonly string[];
  flagValues?: Readonly<Record<string, readonly string[]>>;
  positionalValues?: readonly string[];
}

export const KOOKR_COMPLETION_COMMANDS: readonly CommandCompletion[] = [
  {
    name: 'spawn',
    flags: [
      '-C',
      '--cwd',
      '-a',
      '--agent',
      '--effort',
      '--criteria',
      '--dedupe',
      '--parent-task-id',
      '--no-parent-task',
      '-f',
      '--prompt-file',
      '--json',
      '-h',
      '--help',
    ],
    flagValues: {
      '--agent': ['claude-code', 'codex-cli'],
      '--effort': ['none', 'minimal', 'low', 'medium', 'high', 'xhigh', 'max'],
      '--dedupe': ['warn', 'block', 'skip'],
    },
  },
  {
    name: 'signal',
    positionalValues: ['completion-ready'],
    flags: ['--note', '--task-id', '-h', '--help'],
  },
  {
    name: 'doctor',
    flags: ['--json', '-h', '--help'],
  },
  {
    name: 'status',
    flags: ['--json', '-h', '--help'],
  },
  {
    name: 'ralph',
    subcommands: ['status', 'pause', 'resume', 'cancel'],
    flags: ['--json', '-h', '--help'],
  },
  {
    name: 'drain',
    subcommands: ['status'],
  },
  {
    name: 'resume',
  },
  {
    name: 'maintenance',
    subcommands: ['prune', 'backup'],
    flags: [...MAINTENANCE_PRUNE_FLAGS, ...MAINTENANCE_BACKUP_FLAGS],
  },
  {
    name: 'push',
    subcommands: ['test'],
  },
  {
    name: 'completion',
    subcommands: COMPLETION_SHELLS,
    flags: ['-h', '--help'],
  },
];

export function completionUsage(): string {
  return [
    'Usage: kookr completion <bash|zsh>',
    '',
    'Print a shell completion script to stdout.',
    '',
    'Install examples:',
    '  source <(kookr completion bash)',
    '  kookr completion zsh > "${fpath[1]}/_kookr"',
  ].join('\n');
}

export function getRootCompletionCommands(): string[] {
  return KOOKR_COMPLETION_COMMANDS.map((command) => command.name);
}

export function renderCompletion(shell: CompletionShell): string {
  if (shell === 'bash') return renderBashCompletion();
  return renderZshCompletion();
}

export async function runCompletionCli({
  argv = process.argv.slice(2),
  out = console,
  err = console,
  exit = process.exit,
}: {
  argv?: string[];
  out?: Pick<Console, 'log'>;
  err?: Pick<Console, 'error'>;
  exit?: (code: number) => never;
} = {}): Promise<never | undefined> {
  const [shell, ...rest] = argv;
  if (shell === '-h' || shell === '--help') {
    out.log(completionUsage());
    return exit(0);
  }
  if (!isCompletionShell(shell) || rest.length > 0) {
    err.error(completionUsage());
    return exit(2);
  }
  out.log(renderCompletion(shell));
  return exit(0);
}

function isCompletionShell(value: string | undefined): value is CompletionShell {
  return COMPLETION_SHELLS.includes(value as CompletionShell);
}

function renderBashCompletion(): string {
  const rootWords = shellWords(getRootCompletionCommands());
  const shells = subcommandsFor('completion');
  const agentValues = flagValuesFor('spawn', '--agent');
  const dedupeValues = flagValuesFor('spawn', '--dedupe');
  const effortValues = flagValuesFor('spawn', '--effort');
  const dedupeEqualsValues = equalsFlagValues('--dedupe', dedupeValues);
  const effortEqualsValues = equalsFlagValues('--effort', effortValues);
  const spawnFlags = flagsFor('spawn');
  const signalKinds = positionalValuesFor('signal');
  const signalFlags = flagsFor('signal');
  const doctorFlags = flagsFor('doctor');
  const statusFlags = flagsFor('status');
  const ralphSubcommands = subcommandsFor('ralph');
  const ralphFlags = flagsFor('ralph');
  const drainSubcommands = subcommandsFor('drain');
  const drainFlags = flagsFor('drain');
  const maintenanceSubcommands = subcommandsFor('maintenance');
  const maintenancePruneFlags = shellWords(MAINTENANCE_PRUNE_FLAGS);
  const maintenanceBackupFlags = shellWords(MAINTENANCE_BACKUP_FLAGS);
  const pushSubcommands = subcommandsFor('push');
  const completionFlags = flagsFor('completion');

  return `# bash completion for kookr. Generated by \`kookr completion bash\`.
_kookr()
{
  local cur prev cmd
  COMPREPLY=()
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"
  cmd="\${COMP_WORDS[1]}"

  case "\${prev}" in
    -a|--agent)
      COMPREPLY=( $(compgen -W "${agentValues}" -- "\${cur}") )
      return 0
      ;;
    --effort)
      COMPREPLY=( $(compgen -W "${effortValues}" -- "\${cur}") )
      return 0
      ;;
    --dedupe)
      COMPREPLY=( $(compgen -W "${dedupeValues}" -- "\${cur}") )
      return 0
      ;;
    completion)
      COMPREPLY=( $(compgen -W "${shells}" -- "\${cur}") )
      return 0
      ;;
  esac

  if [[ "\${cur}" == --dedupe=* ]]; then
    COMPREPLY=( $(compgen -W "${dedupeEqualsValues}" -- "\${cur}") )
    return 0
  fi
  if [[ "\${cur}" == --effort=* ]]; then
    COMPREPLY=( $(compgen -W "${effortEqualsValues}" -- "\${cur}") )
    return 0
  fi

  case "\${COMP_CWORD}" in
    1)
      COMPREPLY=( $(compgen -W "${rootWords} -h --help" -- "\${cur}") )
      return 0
      ;;
  esac

  case "\${cmd}" in
    spawn)
      COMPREPLY=( $(compgen -W "${spawnFlags}" -- "\${cur}") )
      ;;
    signal)
      if [[ "\${COMP_CWORD}" == 2 ]]; then
        COMPREPLY=( $(compgen -W "${signalKinds} ${signalFlags}" -- "\${cur}") )
      else
        COMPREPLY=( $(compgen -W "${signalFlags}" -- "\${cur}") )
      fi
      ;;
    status)
      COMPREPLY=( $(compgen -W "${statusFlags}" -- "\${cur}") )
      ;;
    doctor)
      COMPREPLY=( $(compgen -W "${doctorFlags}" -- "\${cur}") )
      ;;
    ralph)
      if [[ "\${COMP_CWORD}" == 2 ]]; then
        COMPREPLY=( $(compgen -W "${ralphSubcommands} ${ralphFlags}" -- "\${cur}") )
      else
        COMPREPLY=( $(compgen -W "${ralphFlags}" -- "\${cur}") )
      fi
      ;;
    drain)
      COMPREPLY=( $(compgen -W "${drainSubcommands} ${drainFlags}" -- "\${cur}") )
      ;;
    resume)
      COMPREPLY=()
      ;;
    maintenance)
      if [[ "\${COMP_CWORD}" == 2 ]]; then
        COMPREPLY=( $(compgen -W "${maintenanceSubcommands}" -- "\${cur}") )
      else
        case "\${COMP_WORDS[2]}" in
          prune)
            COMPREPLY=( $(compgen -W "${maintenancePruneFlags}" -- "\${cur}") )
            ;;
          backup)
            COMPREPLY=( $(compgen -W "${maintenanceBackupFlags}" -- "\${cur}") )
            ;;
          *)
            COMPREPLY=()
            ;;
        esac
      fi
      ;;
    push)
      if [[ "\${COMP_CWORD}" == 2 ]]; then
        COMPREPLY=( $(compgen -W "${pushSubcommands}" -- "\${cur}") )
      fi
      ;;
    completion)
      if [[ "\${COMP_CWORD}" == 2 ]]; then
        COMPREPLY=( $(compgen -W "${shells}" -- "\${cur}") )
      else
        COMPREPLY=( $(compgen -W "${completionFlags}" -- "\${cur}") )
      fi
      ;;
  esac
}
complete -F _kookr kookr`;
}

function renderZshCompletion(): string {
  const rootWords = shellWords(getRootCompletionCommands());
  const shells = subcommandsFor('completion');
  const agentValues = flagValuesFor('spawn', '--agent');
  const dedupeValues = flagValuesFor('spawn', '--dedupe');
  const effortValues = flagValuesFor('spawn', '--effort');
  const dedupeEqualsValues = equalsFlagValues('--dedupe', dedupeValues);
  const effortEqualsValues = equalsFlagValues('--effort', effortValues);
  const spawnFlags = flagsFor('spawn');
  const signalKinds = positionalValuesFor('signal');
  const signalFlags = flagsFor('signal');
  const doctorFlags = flagsFor('doctor');
  const statusFlags = flagsFor('status');
  const ralphSubcommands = subcommandsFor('ralph');
  const ralphFlags = flagsFor('ralph');
  const drainSubcommands = subcommandsFor('drain');
  const drainFlags = flagsFor('drain');
  const maintenanceSubcommands = subcommandsFor('maintenance');
  const maintenancePruneFlags = shellWords(MAINTENANCE_PRUNE_FLAGS);
  const maintenanceBackupFlags = shellWords(MAINTENANCE_BACKUP_FLAGS);
  const pushSubcommands = subcommandsFor('push');
  const completionFlags = flagsFor('completion');

  return `#compdef kookr
# zsh completion for kookr. Generated by \`kookr completion zsh\`.
_kookr()
{
  local -a root_commands completion_shells
  root_commands=(${rootWords})
  completion_shells=(${shells})

  if (( CURRENT == 2 )); then
    compadd -- $root_commands -h --help
    return
  fi

  case "$words[2]" in
    spawn)
      case "$words[CURRENT]" in
        --dedupe=*) compadd -- ${dedupeEqualsValues}; return ;;
        --effort=*) compadd -- ${effortEqualsValues}; return ;;
      esac
      case "$words[CURRENT-1]" in
        -a|--agent) compadd ${agentValues}; return ;;
        --effort) compadd ${effortValues}; return ;;
        --dedupe) compadd ${dedupeValues}; return ;;
      esac
      compadd -- ${spawnFlags}
      ;;
    signal)
      if (( CURRENT == 3 )); then
        compadd -- ${signalKinds} ${signalFlags}
      else
        compadd -- ${signalFlags}
      fi
      ;;
    status)
      compadd -- ${statusFlags}
      ;;
    doctor)
      compadd -- ${doctorFlags}
      ;;
    ralph)
      if (( CURRENT == 3 )); then
        compadd -- ${ralphSubcommands} ${ralphFlags}
      else
        compadd -- ${ralphFlags}
      fi
      ;;
    drain)
      compadd -- ${drainSubcommands} ${drainFlags}
      ;;
    resume)
      ;;
    maintenance)
      if (( CURRENT == 3 )); then
        compadd ${maintenanceSubcommands}
      else
        case "$words[3]" in
          prune) compadd -- ${maintenancePruneFlags} ;;
          backup) compadd -- ${maintenanceBackupFlags} ;;
        esac
      fi
      ;;
    push)
      if (( CURRENT == 3 )); then
        compadd ${pushSubcommands}
      fi
      ;;
    completion)
      if (( CURRENT == 3 )); then
        compadd -- $completion_shells
      else
        compadd -- ${completionFlags}
      fi
      ;;
  esac
}

_kookr "$@"`;
}

function flagsFor(commandName: string): string {
  const command = KOOKR_COMPLETION_COMMANDS.find((item) => item.name === commandName);
  return shellWords(command?.flags ?? []);
}

function subcommandsFor(commandName: string): string {
  const command = KOOKR_COMPLETION_COMMANDS.find((item) => item.name === commandName);
  return shellWords(command?.subcommands ?? []);
}

function positionalValuesFor(commandName: string): string {
  const command = KOOKR_COMPLETION_COMMANDS.find((item) => item.name === commandName);
  return shellWords(command?.positionalValues ?? []);
}

function flagValuesFor(commandName: string, flag: string): string {
  const command = KOOKR_COMPLETION_COMMANDS.find((item) => item.name === commandName);
  return shellWords(command?.flagValues?.[flag] ?? []);
}

function equalsFlagValues(flag: string, values: string): string {
  return values
    .split(' ')
    .filter(Boolean)
    .map((value) => `${flag}=${value}`)
    .join(' ');
}

function shellWords(words: readonly string[]): string {
  return words.join(' ');
}
