/**
 * Pre-scripted ANSI terminal content for demo agent sessions.
 * Each function returns a string of terminal output that looks like
 * a real Claude Code agent working on a task.
 */

// ANSI color codes
const R = '\x1b[0m';     // Reset
const B = '\x1b[1m';     // Bold
const D = '\x1b[2m';     // Dim
const C = '\x1b[36m';    // Cyan
const G = '\x1b[32m';    // Green
const Y = '\x1b[33m';    // Yellow
const BL = '\x1b[34m';   // Blue
const M = '\x1b[35m';    // Magenta
const W = '\x1b[37m';    // White
const GR = '\x1b[90m';   // Gray

function line(n: number): string {
  return `${GR}${String(n).padStart(3)}${R} ${GR}│${R}`;
}

/** Agent 1: Fix JWT token refresh — reads code, edits, runs tests, hits permission block */
export function jwtFixContent(): string {
  return [
    `${D}╭──────────────────────────────────────────────────────────────╮${R}`,
    `${D}│${R}  ${B}${C}Claude Code${R}  ${D}(claude-sonnet-4-6)${R}                               ${D}│${R}`,
    `${D}╰──────────────────────────────────────────────────────────────╯${R}`,
    ``,
    `${B}${W}> ${R}${G}Read${R} ${D}src/auth/token.ts${R}`,
    ``,
    `${line(1)} import { verify, sign } from '${Y}jsonwebtoken${R}';`,
    `${line(2)} import { config } from '${Y}../config${R}';`,
    `${line(3)}`,
    `${line(4)} export function ${BL}refreshToken${R}(token: string) {`,
    `${line(5)}   const decoded = verify(token, config.${Y}JWT_SECRET${R});`,
    `${line(6)}   if (typeof decoded === '${G}string${R}') {`,
    `${line(7)}     throw new Error('${G}Invalid token payload${R}');`,
    `${line(8)}   }`,
    `${line(9)}   const exp = Math.floor(Date.now() / 1000) + 3600;`,
    `${line(10)}   return sign({ ...decoded, exp }, config.${Y}JWT_SECRET${R});`,
    `${line(11)} }`,
    ``,
    `${B}${W}> ${R}${G}Edit${R} ${D}src/auth/token.ts${R}`,
    `  ${D}Replacing lines 5-9 with refreshed token logic...${R}`,
    ``,
    `${B}${W}> ${R}${BL}Bash${R} ${D}npm test -- --grep "token"${R}`,
    ``,
    `  ${W}PASS${R} ${D}src/auth/__tests__/${R}token.test.ts`,
    `    ${G}✓${R} refreshToken returns a new token ${GR}(3ms)${R}`,
    `    ${G}✓${R} refreshToken rejects expired tokens ${GR}(1ms)${R}`,
    `    ${G}✓${R} refreshToken preserves user claims ${GR}(2ms)${R}`,
    `    ${G}✓${R} refreshToken extends expiration ${GR}(1ms)${R}`,
    ``,
    `  ${B}${G}Tests:${R}   4 passed, 4 total`,
    `  ${B}${W}Time:${R}    0.84s`,
    ``,
    `${B}${W}> ${R}${G}Read${R} ${D}src/auth/middleware.ts${R}`,
    ``,
    `${line(1)} import { refreshToken } from '${Y}./token${R}';`,
    `${line(2)}`,
    `${line(3)} export async function ${BL}authMiddleware${R}(req, res, next) {`,
    `${line(4)}   const token = req.headers.authorization?.split(' ')[1];`,
    `${line(5)}   if (!token) return res.status(401).json({ error: '${G}No token${R}' });`,
    `${line(6)}   try {`,
    `${line(7)}     req.user = verify(token, config.JWT_SECRET);`,
    `${line(8)}     next();`,
    `${line(9)}   } catch {`,
    `${line(10)}     res.status(403).json({ error: '${G}Invalid token${R}' });`,
    `${line(11)}   }`,
    `${line(12)} }`,
    ``,
    `${B}${W}> ${R}${BL}Bash${R} ${D}rm -rf node_modules && npm install${R}`,
    ``,
    `  ${Y}⚠ Permission required${R}`,
    `  Tool: ${W}Bash${R}`,
    `  Command: ${D}rm -rf node_modules && npm install${R}`,
    ``,
  ].join('\n');
}

/** Agent 2: Add pagination — reads routes, greps patterns, edits code */
export function paginationContent(): string {
  return [
    `${D}╭──────────────────────────────────────────────────────────────╮${R}`,
    `${D}│${R}  ${B}${C}Claude Code${R}  ${D}(claude-sonnet-4-6)${R}                               ${D}│${R}`,
    `${D}╰──────────────────────────────────────────────────────────────╯${R}`,
    ``,
    `${B}${W}> ${R}${G}Read${R} ${D}src/routes/users.ts${R}`,
    ``,
    `${line(1)} import { Hono } from '${Y}hono${R}';`,
    `${line(2)} import { db } from '${Y}../db${R}';`,
    `${line(3)}`,
    `${line(4)} export const users = new Hono();`,
    `${line(5)}`,
    `${line(6)} users.get('${G}/${R}', async (c) => {`,
    `${line(7)}   const rows = await db.query('${G}SELECT * FROM users${R}');`,
    `${line(8)}   return c.json(rows);`,
    `${line(9)} });`,
    ``,
    `${B}${W}> ${R}${M}Grep${R} ${D}pattern: "cursor|offset|limit" in src/${R}`,
    ``,
    `  ${D}src/routes/users.ts:7${R}     ${W}const rows = await db.query(...)${R}`,
    `  ${D}src/db.ts:23${R}              ${W}export async function paginate(table, cursor, limit)${R}`,
    `  ${D}src/types.ts:45${R}           ${W}interface PaginationParams { cursor?: string; limit: number }${R}`,
    ``,
    `${B}${W}> ${R}${G}Edit${R} ${D}src/routes/users.ts${R}`,
    `  ${D}Adding cursor-based pagination with limit parameter...${R}`,
    ``,
    `${B}${W}> ${R}${BL}Bash${R} ${D}npm test -- --grep "pagination"${R}`,
    ``,
    `  ${W}PASS${R} ${D}src/routes/__tests__/${R}users.test.ts`,
    `    ${G}✓${R} GET /users returns paginated results ${GR}(12ms)${R}`,
    `    ${G}✓${R} GET /users?cursor=abc returns next page ${GR}(8ms)${R}`,
    `    ${G}✓${R} GET /users?limit=5 respects limit ${GR}(3ms)${R}`,
    `    ${G}✓${R} GET /users returns empty for last page ${GR}(2ms)${R}`,
    ``,
    `  ${B}${G}Tests:${R}   4 passed, 4 total`,
    `  ${B}${W}Time:${R}    1.23s`,
    ``,
    `${B}${W}> ${R}${BL}Bash${R} ${D}gh pr create --title "feat: add pagination" --body "..."${R}`,
    ``,
    `  ${G}✓${R} Created pull request ${W}#42${R}`,
    `  ${D}https://github.com/acme/webapp/pull/42${R}`,
    ``,
  ].join('\n');
}

/** Agent 3: Refactor cache — reads code, then stops to ask a question */
export function cacheRefactorContent(): string {
  return [
    `${D}╭──────────────────────────────────────────────────────────────╮${R}`,
    `${D}│${R}  ${B}${C}Claude Code${R}  ${D}(claude-sonnet-4-6)${R}                               ${D}│${R}`,
    `${D}╰──────────────────────────────────────────────────────────────╯${R}`,
    ``,
    `${B}${W}> ${R}${G}Read${R} ${D}src/cache/index.ts${R}`,
    ``,
    `${line(1)} import NodeCache from '${Y}node-cache${R}';`,
    `${line(2)}`,
    `${line(3)} const cache = new NodeCache({ stdTTL: 300 });`,
    `${line(4)}`,
    `${line(5)} export function ${BL}get${R}<T>(key: string): T | undefined {`,
    `${line(6)}   return cache.get<T>(key);`,
    `${line(7)} }`,
    `${line(8)}`,
    `${line(9)} export function ${BL}set${R}<T>(key: string, val: T, ttl?: number) {`,
    `${line(10)}   cache.set(key, val, ttl ?? 300);`,
    `${line(11)} }`,
    ``,
    `${B}${W}> ${R}${G}Read${R} ${D}src/cache/store.ts${R}`,
    ``,
    `${line(1)} import { get, set } from '${Y}./index${R}';`,
    `${line(2)}`,
    `${line(3)} export class ${BL}CacheStore${R} {`,
    `${line(4)}   constructor(private prefix: string) {}`,
    `${line(5)}`,
    `${line(6)}   async ${BL}fetch${R}(key: string) {`,
    `${line(7)}     const cached = get(\`\${this.prefix}:\${key}\`);`,
    `${line(8)}     if (cached) return cached;`,
    `${line(9)}     // fallback to database...`,
    `${line(10)}   }`,
    `${line(11)} }`,
    ``,
    `${B}${W}> ${R}${M}Grep${R} ${D}pattern: "redis|memcached|ioredis" in package.json${R}`,
    ``,
    `  ${D}No matches found${R}`,
    ``,
    `  I've analyzed the codebase and found the current cache layer uses`,
    `  ${W}node-cache${R} (in-memory only). To support Redis, I have two options:`,
    ``,
    `  ${Y}1.${R} ${B}Redis${R} — persistent, supports pub/sub, larger memory footprint`,
    `  ${Y}2.${R} ${B}Memcached${R} — simpler protocol, pure key-value, no persistence`,
    ``,
    `  ${B}${C}?${R} Should I use Redis or Memcached for the cache layer?`,
    `    Redis has persistence but Memcached is simpler.`,
    ``,
  ].join('\n');
}

/** Agent 4: Add rate limiting — reads routes, checks middleware, asks about storage strategy */
export function rateLimitContent(): string {
  return [
    `${D}╭──────────────────────────────────────────────────────────────╮${R}`,
    `${D}│${R}  ${B}${C}Claude Code${R}  ${D}(claude-sonnet-4-6)${R}                               ${D}│${R}`,
    `${D}╰──────────────────────────────────────────────────────────────╯${R}`,
    ``,
    `${B}${W}> ${R}${G}Read${R} ${D}src/middleware/rate-limit.ts${R}`,
    ``,
    `${line(1)} import { Context, Next } from '${Y}hono${R}';`,
    `${line(2)}`,
    `${line(3)} const windowMs = 60 * 1000;`,
    `${line(4)} const hits = new Map<string, number[]>();`,
    `${line(5)}`,
    `${line(6)} export function ${BL}rateLimit${R}(limit: number) {`,
    `${line(7)}   return async (c: Context, next: Next) => {`,
    `${line(8)}     const ip = c.req.header('${G}x-forwarded-for${R}') ?? '${G}unknown${R}';`,
    `${line(9)}     const now = Date.now();`,
    `${line(10)}     const window = (hits.get(ip) ?? []).filter(t => t > now - windowMs);`,
    `${line(11)}     if (window.length >= limit) {`,
    `${line(12)}       return c.json({ error: '${G}Too many requests${R}' }, 429);`,
    `${line(13)}     }`,
    `${line(14)}     hits.set(ip, [...window, now]);`,
    `${line(15)}     await next();`,
    `${line(16)}   };`,
    `${line(17)} }`,
    ``,
    `${B}${W}> ${R}${M}Grep${R} ${D}pattern: "rateLimit|rate-limit" in src/routes/${R}`,
    ``,
    `  ${D}src/routes/users.ts:3${R}      ${W}import { rateLimit } from '../middleware/rate-limit';${R}`,
    `  ${D}src/routes/users.ts:8${R}      ${W}users.use(rateLimit(100));${R}`,
    `  ${D}src/routes/auth.ts:5${R}       ${W}auth.use(rateLimit(20));${R}`,
    ``,
    `${B}${W}> ${R}${G}Read${R} ${D}src/routes/users.ts${R}`,
    ``,
    `${line(1)} import { Hono } from '${Y}hono${R}';`,
    `${line(2)} import { db } from '${Y}../db${R}';`,
    `${line(3)} import { rateLimit } from '${Y}../middleware/rate-limit${R}';`,
    `${line(4)}`,
    `${line(5)} export const users = new Hono();`,
    `${line(6)}`,
    `${line(7)} // Rate limit: 100 req/min per IP`,
    `${line(8)} users.use(rateLimit(100));`,
    ``,
    `  I found the existing rate limiter. It stores request windows in memory,`,
    `  which is fine for one local instance but will drift once the API runs`,
    `  behind more than one process.`,
    ``,
    `  ${B}${C}?${R} Rate-limit storage decision needed before I wire the middleware.`,
    `    Ship in-memory TTL now with a Redis storage interface, or add Redis immediately?`,
    ``,
  ].join('\n');
}

/** Agent 5: Refactor auth middleware — reads, edits, runs tests, completes */
export function authRefactorContent(): string {
  return [
    `${D}╭──────────────────────────────────────────────────────────────╮${R}`,
    `${D}│${R}  ${B}${C}Claude Code${R}  ${D}(claude-sonnet-4-6)${R}                               ${D}│${R}`,
    `${D}╰──────────────────────────────────────────────────────────────╯${R}`,
    ``,
    `${B}${W}> ${R}${G}Read${R} ${D}src/auth/middleware.ts${R}`,
    ``,
    `${line(1)} import { verify } from '${Y}jsonwebtoken${R}';`,
    `${line(2)} import { config } from '${Y}../config${R}';`,
    `${line(3)}`,
    `${line(4)} export async function ${BL}authMiddleware${R}(req, res, next) {`,
    `${line(5)}   const token = req.headers.authorization?.split(' ')[1];`,
    `${line(6)}   if (!token) return res.status(401).json({ error: '${G}No token${R}' });`,
    `${line(7)}   try {`,
    `${line(8)}     req.user = verify(token, config.JWT_SECRET);`,
    `${line(9)}     next();`,
    `${line(10)}   } catch {`,
    `${line(11)}     res.status(403).json({ error: '${G}Invalid token${R}' });`,
    `${line(12)}   }`,
    `${line(13)} }`,
    ``,
    `${B}${W}> ${R}${G}Edit${R} ${D}src/auth/middleware.ts${R}`,
    `  ${D}Refactoring to async/await pattern with proper error types...${R}`,
    ``,
    `${B}${W}> ${R}${G}Edit${R} ${D}src/auth/types.ts${R}`,
    `  ${D}Adding AuthError and TokenExpiredError types...${R}`,
    ``,
    `${B}${W}> ${R}${BL}Bash${R} ${D}npm test -- --grep "auth"${R}`,
    ``,
    `  ${W}PASS${R} ${D}src/auth/__tests__/${R}middleware.test.ts`,
    `    ${G}✓${R} rejects request without token ${GR}(2ms)${R}`,
    `    ${G}✓${R} rejects expired token with AuthError ${GR}(3ms)${R}`,
    `    ${G}✓${R} passes valid token through ${GR}(1ms)${R}`,
    `    ${G}✓${R} attaches decoded user to request ${GR}(2ms)${R}`,
    `    ${G}✓${R} handles malformed token gracefully ${GR}(1ms)${R}`,
    ``,
    `  ${W}PASS${R} ${D}src/auth/__tests__/${R}types.test.ts`,
    `    ${G}✓${R} AuthError has correct name and status ${GR}(1ms)${R}`,
    `    ${G}✓${R} TokenExpiredError extends AuthError ${GR}(1ms)${R}`,
    ``,
    `  ${B}${G}Tests:${R}   7 passed, 7 total`,
    `  ${B}${W}Time:${R}    0.91s`,
    ``,
    `  ${G}✓${R} All tests passing. The auth middleware has been refactored to:`,
    `  - Use async/await instead of callbacks`,
    `  - Throw typed AuthError/TokenExpiredError`,
    `  - Return proper 401/403 status codes`,
    ``,
  ].join('\n');
}

/** Agent with merge conflict — git operations show conflict markers */
export function mergeConflictContent(): string {
  return [
    `${D}╭──────────────────────────────────────────────────────────────╮${R}`,
    `${D}│${R}  ${B}${C}Claude Code${R}  ${D}(claude-sonnet-4-6)${R}                               ${D}│${R}`,
    `${D}╰──────────────────────────────────────────────────────────────╯${R}`,
    ``,
    `${B}${W}> ${R}${BL}Bash${R} ${D}git pull origin main${R}`,
    ``,
    `  Auto-merging src/auth.ts`,
    `  ${Y}CONFLICT${R} (content): Merge conflict in ${W}src/auth.ts${R}`,
    `  Automatic merge failed; fix conflicts and then commit the result.`,
    ``,
    `${B}${W}> ${R}${G}Read${R} ${D}src/auth.ts${R}`,
    ``,
    `${line(12)} <<<<<<< HEAD`,
    `${line(13)}   const token = sign(payload, config.${Y}JWT_SECRET${R}, { expiresIn: '${G}1h${R}' });`,
    `${line(14)} =======`,
    `${line(15)}   const token = sign(payload, config.${Y}JWT_SECRET${R}, { expiresIn: '${G}24h${R}' });`,
    `${line(16)} >>>>>>> origin/main`,
    ``,
  ].join('\n');
}
